Repository Likelion-To-Star/backend, pull requests merged in 2024-10, with the labels that each got.

#3 Ci/1 ci deploy choi76
  .github/workflows/gradle.yml
  Dockerfile
  build.gradle
Labels: :white_check_mark: Add, :construction_worker: CI

#6 Feat/2 signup signin choi76
  src/main/java/com/likelion/tostar/domain/member/dto/JoinDTO.java
  src/main/java/com/likelion/tostar/domain/member/entity/Member.java
  src/main/java/com/likelion/tostar/domain/member/repository/MemberRepository.java
  src/main/java/com/likelion/tostar/domain/member/service/MemberService.java
  src/main/java/com/likelion/tostar/domain/user/controller/UserController.java
  src/main/java/com/likelion/tostar/domain/user/converter/UserConverter.java
  src/main/java/com/likelion/tostar/domain/user/dto/LoginRequestDTO.java
  src/main/java/com/likelion/tostar/domain/user/dto/UserInfoDTO.java
  src/main/java/com/likelion/tostar/domain/user/entity/User.java
  src/main/java/com/likelion/tostar/domain/user/repository/UserRepository.java
  src/main/java/com/likelion/tostar/domain/user/service/UserService.java
  src/main/java/com/likelion/tostar/domain/user/service/UserServiceImpl.java
  src/main/java/com/likelion/tostar/global/config/SecurityConfig.java
  src/main/java/com/likelion/tostar/global/jwt/dto/CustomUserDetails.java
  src/main/java/com/likelion/tostar/global/jwt/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/likelion/tostar/global/jwt/service/CustomUserDetailsService.java
Labels: :sparkles: Feat, :technologist: choi76, :rotating_light: Fix

#7 Feat/4 s3 choi76
  build.gradle
  src/main/java/com/likelion/tostar/global/s3/config/S3Config.java
  src/main/java/com/likelion/tostar/global/s3/controller/S3Controller.java
  src/main/java/com/likelion/tostar/global/s3/service/S3Service.java
Labels: :sparkles: Feat, :white_check_mark: Add, :technologist: choi76

#9 Feat/5 edit user info choi76
  src/main/java/com/likelion/tostar/domain/user/controller/UserController.java
  src/main/java/com/likelion/tostar/domain/user/converter/UserConverter.java
  src/main/java/com/likelion/tostar/domain/user/dto/UserInfoDTO.java
  src/main/java/com/likelion/tostar/domain/user/dto/UserJoinDTO.java
  src/main/java/com/likelion/tostar/domain/user/entity/User.java
  src/main/java/com/likelion/tostar/domain/user/service/UserService.java
  src/main/java/com/likelion/tostar/domain/user/service/UserServiceImpl.java
  src/main/java/com/likelion/tostar/global/enums/statuscode/ErrorStatus.java
  src/main/java/com/likelion/tostar/global/jwt/service/CustomUserDetailsService.java
Labels: :sparkles: Feat, :technologist: choi76, :rotating_light: Fix

#11 Feat/8 pet image choi76
  src/main/java/com/likelion/tostar/domain/user/controller/UserController.java
  src/main/java/com/likelion/tostar/domain/user/converter/UserConverter.java
  src/main/java/com/likelion/tostar/domain/user/dto/UserInfoDTO.java
  src/main/java/com/likelion/tostar/domain/user/dto/UserJoinDTO.java
  src/main/java/com/likelion/tostar/domain/user/entity/User.java
  src/main/java/com/likelion/tostar/domain/user/service/UserService.java
  src/main/java/com/likelion/tostar/domain/user/service/UserServiceImpl.java
  src/main/java/com/likelion/tostar/global/enums/statuscode/ErrorStatus.java
  src/main/java/com/likelion/tostar/global/s3/service/S3Service.java
Labels: :sparkles: Feat, :technologist: choi76, :rotating_light: Fix

#12 Fix/10 login choi76
  src/main/java/com/likelion/tostar/domain/user/converter/UserConverter.java
  src/main/java/com/likelion/tostar/domain/user/dto/LoginResponseDTO.java
  src/main/java/com/likelion/tostar/domain/user/service/UserServiceImpl.java
Labels: :sparkles: Feat, :technologist: choi76, :rotating_light: Fix

#14 Feat/13 community preview3 choi76
  src/main/java/com/likelion/tostar/domain/community/controller/CommunityController.java
  src/main/java/com/likelion/tostar/domain/community/converter/CommunityConverter.java
  src/main/java/com/likelion/tostar/domain/community/dto/CommunityPreviewResponseDTO.java
  src/main/java/com/likelion/tostar/domain/community/entity/Community.java
  src/main/java/com/likelion/tostar/domain/community/repository/CommunityRepository.java
  src/main/java/com/likelion/tostar/domain/community/service/CommunityService.java
  src/main/java/com/likelion/tostar/domain/community/service/CommunityServiceImpl.java
  src/main/java/com/likelion/tostar/domain/user/converter/UserConverter.java
  src/main/java/com/likelion/tostar/domain/user/dto/LoginResponseDTO.java
  src/main/java/com/likelion/tostar/domain/user/entity/User.java
Labels: :sparkles: Feat, :technologist: choi76

#18 Feat/15 create community choi76
  src/main/java/com/likelion/tostar/domain/community/controller/CommunityController.java
  src/main/java/com/likelion/tostar/domain/community/converter/CommunityConverter.java
  src/main/java/com/likelion/tostar/domain/community/dto/CommunityFormDTO.java
  src/main/java/com/likelion/tostar/domain/community/entity/Community.java
  src/main/java/com/likelion/tostar/domain/community/entity/Member.java
  src/main/java/com/likelion/tostar/domain/community/service/CommunityCommandService.java
  src/main/java/com/likelion/tostar/domain/community/service/CommunityCommandServiceImpl.java
  src/main/java/com/likelion/tostar/domain/community/service/CommunityQueryService.java
  src/main/java/com/likelion/tostar/domain/community/service/CommunityQueryServiceImpl.java
  src/main/java/com/likelion/tostar/domain/user/entity/User.java
Labels: :sparkles: Feat, :technologist: choi76

#19 Feat/16 community edit choi76
  src/main/java/com/likelion/tostar/domain/community/controller/CommunityController.java
  src/main/java/com/likelion/tostar/domain/community/entity/Community.java
  src/main/java/com/likelion/tostar/domain/community/service/CommunityCommandService.java
  src/main/java/com/likelion/tostar/domain/community/service/CommunityCommandServiceImpl.java
  src/main/java/com/likelion/tostar/domain/user/service/UserServiceImpl.java
  src/main/java/com/likelion/tostar/global/enums/statuscode/ErrorStatus.java
  src/main/java/com/likelion/tostar/global/s3/service/S3Service.java
Labels: :sparkles: Feat, :technologist: choi76, :recycle: Refactor

#21 Feat/17 delete community choi76
  src/main/java/com/likelion/tostar/domain/community/controller/CommunityController.java
  src/main/java/com/likelion/tostar/domain/community/service/CommunityCommandService.java
  src/main/java/com/likelion/tostar/domain/community/service/CommunityCommandServiceImpl.java
Labels: :sparkles: Feat, :technologist: choi76

#24 ✏️ [fix] 커뮤니티 미리보기 DTO 반환값 수정
  src/main/java/com/likelion/tostar/domain/community/converter/CommunityConverter.java
  src/main/java/com/likelion/tostar/domain/community/dto/CommunityPreviewResponseDTO.java
Labels: :technologist: choi76, :rotating_light: Fix

#25 Feat/22 community join choi76
  src/main/java/com/likelion/tostar/domain/community/controller/CommunityController.java
  src/main/java/com/likelion/tostar/domain/community/entity/Community.java
  src/main/java/com/likelion/tostar/domain/community/repository/MemberRepository.java
  src/main/java/com/likelion/tostar/domain/community/service/CommunityCommandService.java
  src/main/java/com/likelion/tostar/domain/community/service/CommunityCommandServiceImpl.java
  src/main/java/com/likelion/tostar/global/enums/statuscode/ErrorStatus.java
Labels: :sparkles: Feat, :technologist: choi76

#26 Feat/23 leave community choi76
  src/main/java/com/likelion/tostar/domain/community/controller/CommunityController.java
  src/main/java/com/likelion/tostar/domain/community/entity/Community.java
  src/main/java/com/likelion/tostar/domain/community/service/CommunityCommandService.java
  src/main/java/com/likelion/tostar/domain/community/service/CommunityCommandServiceImpl.java
  src/main/java/com/likelion/tostar/global/enums/statuscode/ErrorStatus.java
Labels: :sparkles: Feat, :technologist: choi76

#29 Feat/27 preview all community choi76
  src/main/java/com/likelion/tostar/domain/community/controller/CommunityController.java
  src/main/java/com/likelion/tostar/domain/community/entity/Community.java
  src/main/java/com/likelion/tostar/domain/community/service/CommunityQueryService.java
  src/main/java/com/likelion/tostar/domain/community/service/CommunityQueryServiceImpl.java
Labels: :sparkles: Feat, :technologist: choi76

#30 Feat/28 preview my community choi76
  src/main/java/com/likelion/tostar/domain/community/controller/CommunityController.java
  src/main/java/com/likelion/tostar/domain/community/entity/Member.java
  src/main/java/com/likelion/tostar/domain/community/repository/MemberRepository.java
  src/main/java/com/likelion/tostar/domain/community/service/CommunityQueryService.java
  src/main/java/com/likelion/tostar/domain/community/service/CommunityQueryServiceImpl.java
Labels: :sparkles: Feat, :technologist: choi76

#32 Feat/31 community preview choi76
  src/main/java/com/likelion/tostar/domain/community/controller/CommunityController.java
  src/main/java/com/likelion/tostar/domain/community/converter/CommunityConverter.java
  src/main/java/com/likelion/tostar/domain/community/dto/CommunityProfileResponseDTO.java
  src/main/java/com/likelion/tostar/domain/community/service/CommunityQueryService.java
  src/main/java/com/likelion/tostar/domain/community/service/CommunityQueryServiceImpl.java
Labels: :sparkles: Feat, :technologist: choi76

#38 [Settings] 필요한 entity 생성 및 기본 정보 세팅
  src/main/java/com/likelion/tostar/domain/letter/entity/Letter.java
  src/main/java/com/likelion/tostar/domain/letter/entity/SenderType.java
  src/main/java/com/likelion/tostar/domain/letter/repository/LetterRepository.java
  src/main/java/com/likelion/tostar/domain/relationship/entity/Relationship.java
  src/main/java/com/likelion/tostar/domain/relationship/repository/RelationshipRepository.java
Labels: :rainbow: khyaejin, :wrench: Settings

#39 🔧 [chore] CORS 설정 추가
  src/main/java/com/likelion/tostar/global/config/SecurityConfig.java
Labels: :sparkles: Feat, :technologist: choi76

#40 ✨ [Feat] 회원 검색
  src/main/java/com/likelion/tostar/domain/user/controller/UserController.java
  src/main/java/com/likelion/tostar/domain/user/dto/UserSearchDto.java
  src/main/java/com/likelion/tostar/domain/user/entity/User.java
  src/main/java/com/likelion/tostar/domain/user/repository/UserRepository.java
  src/main/java/com/likelion/tostar/domain/user/service/UserService.java
  src/main/java/com/likelion/tostar/domain/user/service/UserServiceImpl.java
Labels: :sparkles: Feat, :rainbow: khyaejin

#41 ✨ [Feat] 친구 추가
  src/main/java/com/likelion/tostar/domain/user/controller/UserController.java
  src/main/java/com/likelion/tostar/domain/user/dto/AddFriendDto.java
  src/main/java/com/likelion/tostar/domain/user/service/UserService.java
  src/main/java/com/likelion/tostar/domain/user/service/UserServiceImpl.java
  src/main/java/com/likelion/tostar/global/enums/statuscode/ErrorStatus.java
Labels: :sparkles: Feat, :rainbow: khyaejin

#42 ✨ [Feat] 친구 전체 조회 api 구현
  src/main/java/com/likelion/tostar/domain/relationship/repository/RelationshipRepository.java
  src/main/java/com/likelion/tostar/domain/user/controller/UserController.java
  src/main/java/com/likelion/tostar/domain/user/dto/AddFriendDto.java
  src/main/java/com/likelion/tostar/domain/user/dto/SearchFriendListDto.java
  src/main/java/com/likelion/tostar/domain/user/service/UserService.java
  src/main/java/com/likelion/tostar/domain/user/service/UserServiceImpl.java
  src/main/java/com/likelion/tostar/global/jwt/dto/CustomUserDetails.java
Labels: :sparkles: Feat, :rainbow: khyaejin

#44 ✨ [Feat] 편지 전송 api 구현
  src/main/java/com/likelion/tostar/domain/letter/controller/LetterController.java
  src/main/java/com/likelion/tostar/domain/letter/dto/LetterPostRequestDto.java
  src/main/java/com/likelion/tostar/domain/letter/repository/LetterRepository.java
  src/main/java/com/likelion/tostar/domain/letter/service/LetterService.java
  src/main/java/com/likelion/tostar/domain/letter/service/LetterServiceImpl.java
  src/main/java/com/likelion/tostar/domain/user/service/UserServiceImpl.java
  src/main/java/com/likelion/tostar/global/openAi/config/OpenAiConfig.java
  src/main/java/com/likelion/tostar/global/openAi/dto/ChatGPTRequest.java
  src/main/java/com/likelion/tostar/global/openAi/dto/ChatGPTResponse.java
  src/main/java/com/likelion/tostar/global/openAi/dto/Message.java
Labels: :sparkles: Feat, :rainbow: khyaejin

#47 ✏️ [Fix] 편지 전송 - 프롬프트 수정
  src/main/java/com/likelion/tostar/domain/letter/controller/LetterController.java
  src/main/java/com/likelion/tostar/domain/letter/dto/LetterPostDto.java
  src/main/java/com/likelion/tostar/domain/letter/entity/Letter.java
  src/main/java/com/likelion/tostar/domain/letter/service/LetterService.java
  src/main/java/com/likelion/tostar/domain/letter/service/LetterServiceImpl.java
  src/main/java/com/likelion/tostar/global/enums/statuscode/ErrorStatus.java
  src/main/java/com/likelion/tostar/global/openAi/config/OpenAiConfig.java
  src/main/java/com/likelion/tostar/global/openAi/dto/ChatGPTRequest.java
  src/main/java/com/likelion/tostar/global/openAi/dto/ChatGPTResponse.java
Labels: :rotating_light: Fix, :rainbow: khyaejin

#48 ✨ [Feat] 편지 목록 전체 조회 api 구현
  src/main/java/com/likelion/tostar/domain/letter/controller/LetterController.java
  src/main/java/com/likelion/tostar/domain/letter/dto/LetterSearchListDto.java
  src/main/java/com/likelion/tostar/domain/letter/entity/Letter.java
  src/main/java/com/likelion/tostar/domain/letter/entity/SenderType.java
  src/main/java/com/likelion/tostar/domain/letter/repository/LetterRepository.java
  src/main/java/com/likelion/tostar/domain/letter/service/LetterService.java
  src/main/java/com/likelion/tostar/domain/letter/service/LetterServiceImpl.java
  src/main/java/com/likelion/tostar/domain/user/service/UserServiceImpl.java
  src/main/java/com/likelion/tostar/global/entity/BaseEntity.java
Labels: :sparkles: Feat, :rainbow: khyaejin

#50 ✨ [Feat] 편지 상세 조회 api 구현
  src/main/java/com/likelion/tostar/domain/letter/controller/LetterController.java
  src/main/java/com/likelion/tostar/domain/letter/dto/LetterSearchDetailDto.java
  src/main/java/com/likelion/tostar/domain/letter/service/LetterService.java
  src/main/java/com/likelion/tostar/domain/letter/service/LetterServiceImpl.java
  src/main/java/com/likelion/tostar/global/enums/statuscode/ErrorStatus.java
Labels: :sparkles: Feat, :rainbow: khyaejin

#51 ✏️ [Fix] 편지 관련 문제 해결 - SenderType 변경사항 기존 DB에 반영
  src/main/java/com/likelion/tostar/domain/letter/service/LetterServiceImpl.java
  src/main/java/com/likelion/tostar/domain/user/service/UserServiceImpl.java
Labels: :rotating_light: Fix, :rainbow: khyaejin

#54 🎨 [Chore] 편지 전송 - 프롬프트 수정
  src/main/java/com/likelion/tostar/domain/letter/service/LetterServiceImpl.java
Labels: :recycle: Refactor, :rainbow: khyaejin, 🎨 Chore
